import {
  Activity,
  Award,
  Brain,
  Building,
  ChartColumn,
  Check,
  Clapperboard,
  Clock,
  CodeXml,
  Coffee,
  Copy,
  Crown,
  DollarSign,
  Dna,
  Download,
  Flame,
  Gamepad2,
  Globe,
  Heart,
  House,
  Info,
  Landmark,
  Layers,
  Lock,
  Medal,
  Megaphone,
  Menu,
  MonitorPlay,
  MousePointerClick,
  Network,
  Newspaper,
  Orbit,
  Pencil,
  Pizza,
  RadioTower,
  Satellite,
  Save,
  Server,
  Settings,
  Skull,
  Sparkles,
  Star,
  Store,
  Sun,
  Tent,
  TrendingUp,
  Trophy,
  Upload,
  Users,
  Utensils,
  Video,
  X,
  Zap,
} from '@lucide/svelte';

export const ICONS: Record<string, typeof Sparkles> = {
  activity: Activity,
  award: Award,
  brain: Brain,
  building: Building,
  'chart-column': ChartColumn,
  check: Check,
  clapperboard: Clapperboard,
  clock: Clock,
  'code-xml': CodeXml,
  coffee: Coffee,
  copy: Copy,
  crown: Crown,
  'dollar-sign': DollarSign,
  dna: Dna,
  download: Download,
  flame: Flame,
  'gamepad-2': Gamepad2,
  globe: Globe,
  heart: Heart,
  house: House,
  info: Info,
  landmark: Landmark,
  layers: Layers,
  lock: Lock,
  medal: Medal,
  megaphone: Megaphone,
  menu: Menu,
  'monitor-play': MonitorPlay,
  'mouse-pointer-click': MousePointerClick,
  network: Network,
  newspaper: Newspaper,
  orbit: Orbit,
  pencil: Pencil,
  pizza: Pizza,
  'radio-tower': RadioTower,
  satellite: Satellite,
  save: Save,
  server: Server,
  settings: Settings,
  skull: Skull,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  sun: Sun,
  tent: Tent,
  'trending-up': TrendingUp,
  trophy: Trophy,
  upload: Upload,
  users: Users,
  utensils: Utensils,
  video: Video,
  x: X,
  zap: Zap,
};
