import {
  MoveHorizontal,
  MoveVertical,
  ArrowRight,
  BadgeCheck,
  Bell,
  BellOff,
  Circle,
  Eraser,
  GraduationCap,
  Package,
  PaintBucket,
  Pipette,
  Plus,
  Redo2,
  Square,
  Trash,
  Type,
  Undo2,
  WandSparkles,
  Minus,
  PartyPopper,
  Wifi,
  Bed,
  Binoculars,
  Bot,
  BrainCircuit,
  Briefcase,
  CalendarClock,
  Cat,
  ChartNetwork,
  ChefHat,
  ClipboardList,
  Fish,
  Image,
  Lightbulb,
  Moon as MoonIcon,
  Presentation,
  Projector,
  Refrigerator,
  Share2,
  Sofa,
  Sprout,
  Stethoscope,
  Armchair,
  ArrowDown,
  ArrowUp,
  Bandage,
  Car,
  Castle,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  ChevronRight,
  CircleDot,
  Cpu,
  Crosshair,
  Dice5,
  Dumbbell,
  FaceSlightlyFrowning,
  FaceSlightlySmiling,
  Flag,
  Footprints,
  Gem,
  Hammer,
  Handshake,
  Headphones,
  HeartPulse,
  Keyboard,
  Monitor,
  Moon,
  Mouse,
  Palette,
  RefreshCw,
  Rocket,
  Search,
  Shield,
  Shirt,
  Shuffle,
  Spade,
  Swords,
  Target,
  Thermometer,
  TrendingDown,
  User,
  UserPlus,
  Activity,
  Award,
  Brain,
  Building,
  ChartColumn,
  Check,
  Clapperboard,
  Clock,
  CodeXml,
  Coffee,
  Copy,
  Crown,
  DollarSign,
  Dna,
  Download,
  Flame,
  Gamepad2,
  Globe,
  Heart,
  House,
  Info,
  Landmark,
  Layers,
  Lock,
  Medal,
  Megaphone,
  Menu,
  MonitorPlay,
  MousePointerClick,
  Network,
  Newspaper,
  Orbit,
  Pencil,
  Pizza,
  RadioTower,
  Satellite,
  Save,
  Server,
  Settings,
  Skull,
  Sparkles,
  Star,
  Store,
  Sun,
  Tent,
  TrendingUp,
  Trophy,
  Upload,
  Users,
  Utensils,
  Video,
  Wallet,
  Coins,
  X,
  Zap,
  Music,
  Pin,
  PinOff,
  Volume2,
  VolumeX,
  CircleHelp,
  EyeOff,
} from '@lucide/svelte';

export const ICONS: Record<string, typeof Sparkles> = {
  'move-horizontal': MoveHorizontal,
  'move-vertical': MoveVertical,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  bell: Bell,
  'bell-off': BellOff,
  music: Music,
  pin: Pin,
  'pin-off': PinOff,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  help: CircleHelp,
  'eye-off': EyeOff,
  circle: Circle,
  eraser: Eraser,
  'graduation-cap': GraduationCap,
  package: Package,
  'paint-bucket': PaintBucket,
  pipette: Pipette,
  plus: Plus,
  'redo-2': Redo2,
  square: Square,
  trash: Trash,
  type: Type,
  'undo-2': Undo2,
  'wand-sparkles': WandSparkles,
  minus: Minus,
  'party-popper': PartyPopper,
  wifi: Wifi,
  bed: Bed,
  binoculars: Binoculars,
  bot: Bot,
  'brain-circuit': BrainCircuit,
  briefcase: Briefcase,
  'calendar-clock': CalendarClock,
  cat: Cat,
  'chart-network': ChartNetwork,
  'chef-hat': ChefHat,
  'clipboard-list': ClipboardList,
  fish: Fish,
  image: Image,
  lightbulb: Lightbulb,
  sleep: MoonIcon,
  presentation: Presentation,
  projector: Projector,
  refrigerator: Refrigerator,
  'share-2': Share2,
  sofa: Sofa,
  sprout: Sprout,
  stethoscope: Stethoscope,
  armchair: Armchair,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  bandage: Bandage,
  car: Car,
  castle: Castle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  cpu: Cpu,
  crosshair: Crosshair,
  'dice-5': Dice5,
  dumbbell: Dumbbell,
  'face-slightly-frowning': FaceSlightlyFrowning,
  'face-slightly-smiling': FaceSlightlySmiling,
  flag: Flag,
  footprints: Footprints,
  gem: Gem,
  hammer: Hammer,
  handshake: Handshake,
  headphones: Headphones,
  'heart-pulse': HeartPulse,
  keyboard: Keyboard,
  monitor: Monitor,
  moon: Moon,
  mouse: Mouse,
  palette: Palette,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  search: Search,
  shield: Shield,
  shirt: Shirt,
  shuffle: Shuffle,
  spade: Spade,
  swords: Swords,
  target: Target,
  thermometer: Thermometer,
  'trending-down': TrendingDown,
  user: User,
  'user-plus': UserPlus,
  activity: Activity,
  award: Award,
  brain: Brain,
  building: Building,
  'chart-column': ChartColumn,
  check: Check,
  clapperboard: Clapperboard,
  clock: Clock,
  'code-xml': CodeXml,
  coffee: Coffee,
  copy: Copy,
  crown: Crown,
  'dollar-sign': DollarSign,
  dna: Dna,
  download: Download,
  flame: Flame,
  'gamepad-2': Gamepad2,
  globe: Globe,
  heart: Heart,
  wallet: Wallet,
  coins: Coins,
  house: House,
  info: Info,
  landmark: Landmark,
  layers: Layers,
  lock: Lock,
  medal: Medal,
  megaphone: Megaphone,
  menu: Menu,
  'monitor-play': MonitorPlay,
  'mouse-pointer-click': MousePointerClick,
  network: Network,
  newspaper: Newspaper,
  orbit: Orbit,
  pencil: Pencil,
  pizza: Pizza,
  'radio-tower': RadioTower,
  satellite: Satellite,
  save: Save,
  server: Server,
  settings: Settings,
  skull: Skull,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  sun: Sun,
  tent: Tent,
  'trending-up': TrendingUp,
  trophy: Trophy,
  upload: Upload,
  users: Users,
  utensils: Utensils,
  video: Video,
  x: X,
  zap: Zap,
};
