/**
 * Ultra-lategame audit. Takes the reference save (tests/fixtures/lategame-save.txt) and reports what
 * carries the economy, what pays absurdly, and what is close to breaking. Writes a JSON record and a
 * markdown report.
 *
 *   npx tsx scripts/lategame-audit.ts                      # static checks + 2 short projections
 *   npx tsx scripts/lategame-audit.ts --hours=6 --seeds=3  # longer projections
 *
 * The play-forward half (sell the org, play new runs with the save's Legacy) is the balance simulator:
 *   npx tsx scripts/sim/cli.ts --persona=semi --hours=12 --runs=6 --from=tests/fixtures/lategame-save.txt \
 *     --sellnow --json=output/lategame-audit/play-semi.json
 * This script folds any play-*.json it finds there into the report.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fmt } from '../src/engine/format';
import { legacyFor } from '../src/engine/prestige';
import { computeMods, computeRates } from '../src/engine/economy';
import { allIn, cabinetInfo, merchEnvelope, paybacks, payouts, projectForward, sponsorChain } from './lategame-checks';
import { headrooms, loadLategameSave, log10, measure, settled, sweepAblations } from './lategame-lib';
import type { IncomeSource } from '../src/engine/types';

declare const process: { argv: string[] };
const arg = (k: string, d: string) => process.argv.find((a) => a.startsWith(`--${k}=`))?.slice(k.length + 3) ?? d;
const HOURS = Number(arg('hours', '2'));
const SEEDS = Number(arg('seeds', '2'));
const DIR = arg('dir', 'output/lategame-audit');
const REPORT = arg('report', 'output/lategame-audit/report.md');

const save = loadLategameSave();
const s = settled(save);
const mods = computeMods(s);
const rates = computeRates(s, mods);
const base = measure(s);
const sci = (x: number) => (Number.isFinite(x) ? x.toExponential(2) : String(x));
const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const dur = (sec: number) => (sec < 120 ? `${sec.toFixed(0)}s` : sec < 7200 ? `${(sec / 60).toFixed(0)}m` : sec < 172800 ? `${(sec / 3600).toFixed(1)}h` : `${(sec / 86400).toFixed(1)}d`);
const share = (ledger: Record<IncomeSource, number>) => {
  const tot = Object.values(ledger).reduce((a, b) => a + b, 0);
  return Object.entries(ledger)
    .filter(([, v]) => v > 0)
    .sort((a, b) => b[1] - a[1])
    .map(([k, v]) => `${k} ${pct(v / tot)}`)
    .join(', ');
};

const ablations = sweepAblations(save);
const pay = payouts(save);
const back = paybacks(save);
const cash = back.filter((b) => b.currency === 'cash');
const bank = allIn(save);
const merch = merchEnvelope(save);
const cabinet = cabinetInfo(save);
const sponsor = sponsorChain(save);
const heads = headrooms(save);
const projections = Array.from({ length: SEEDS }, (_, i) => projectForward(save, HOURS, i + 1));

const record = { baseline: base, ablations, payouts: pay, paybacks: back, allIn: bank, merch, cabinet, sponsor, headroom: heads, projections };
mkdirSync(DIR, { recursive: true });
writeFileSync(`${DIR}/static.json`, JSON.stringify(record, null, 1));

// ---------------------------------------------------------------------------
// Markdown
// ---------------------------------------------------------------------------
const L: string[] = [];
const table = (head: string[], rows: string[][]) => {
  L.push(`| ${head.join(' | ')} |`, `| ${head.map(() => '---').join(' | ')} |`, ...rows.map((r) => `| ${r.join(' | ')} |`), '');
};

L.push('# Ultra-lategame audit', '');
L.push(`Reference save: \`tests/fixtures/lategame-save.txt\` (${s.org.name}): ${s.prestige.runs} sales, Legacy level ${sci(s.prestige.level)}, ${sci(s.earnedTotal)} lifetime earnings, every Legacy node owned.`);
L.push('Generated by `npx tsx scripts/lategame-audit.ts`; numbers are for the working tree at the time it ran.', '');

L.push('## Where income comes from', '');
table(
  ['view', 'split'],
  [
    ['steady income now (buffs cleared)', `ops ${pct(base.ops / base.total)}, matches ${pct(base.match / base.total)}, merch ${pct(base.merch / base.total)}`],
    ['this run, booked', share(s.incomeRun)],
    ['all runs, booked', share(s.incomeTotal)],
  ],
);

L.push('## The multiplier stack', '');
table(
  ['term', 'value', 'note'],
  [
    ['Legacy level × per-level %', `x${sci(1 + s.prestige.level * mods.legacyLevelPct)}`, `${sci(s.prestige.level)} levels × ${pct(mods.legacyLevelPct)}, linear in level`],
    ['Trophy cabinet (Superfan)', `x${sci(cabinet.multiplier)}`, `${cabinet.achievements}/${cabinet.possible} achievements, 9 factors; next achievement +${pct(cabinet.marginal)}; complete ×${sci(cabinet.atCompletion)}`],
    ['Fame (fans^0.13 × bonus)', `x${sci(rates.fameMult)}`, `fans ${sci(s.fans)}`],
    ['Sponsors', `x${sci(1 + sponsor.effectivePct)}`, `contracts state +${pct(sponsor.statedPct)}; Agent staff multiplies that by ${sponsor.agentMult.toFixed(1)}`],
    ['Fans multiplier', `x${sci(mods.fansMult)}`, ''],
    ['Prize multiplier', `x${sci(mods.prizeMult)}`, 'applies to match and Invitational prizes'],
    ['Invitational reward multiplier', `x${sci(mods.tournamentRewardMult)}`, ''],
    ['Team rating multiplier', `x${sci(mods.teamRatingMult)}`, ''],
  ],
);

L.push('## What income disappears if it is removed', '');
L.push('Each row removes one thing from a copy of the save and recomputes total income per second. `factor` is income with it over income without.', '');
table(
  ['group', 'thing', 'factor', 'log10'],
  ablations.slice(0, 30).map((a) => [a.group, a.id, `x${fmt(a.factor)}`, log10(a.factor).toFixed(2)]),
);
const legacyRows = ablations.filter((a) => a.group.startsWith('legacy') || a.group.startsWith('dynasty') || a.group.startsWith('challenge') || a.group === 'legends' || a.group === 'charter');
L.push('### Legacy only', '');
table(
  ['group', 'thing', 'cost (pts)', 'factor'],
  legacyRows.map((a) => [a.group, a.id, a.cost !== undefined ? String(a.cost) : '', `x${fmt(a.factor)}`]),
);

L.push('## Lump-sum payouts, in seconds of steady income', '');
table(['payout', 'amount', 'seconds', 'duration'], pay.map((p) => [p.what, sci(p.amount), p.seconds.toFixed(0), dur(p.seconds)]));

L.push('## Merch against operations', '');
table(['case', 'merch ÷ operations income'], merch.map((m) => [m.label, m.merchOverOps.toFixed(2)]));

L.push('## Spending: the next unit of each line', '');
L.push(`Cash on hand is ${dur(s.cash / rates.totalCps)} of income. Payback is the price of one more over the income it adds; elasticity is the % income gained per 1% more of the line.`, '');
table(
  ['line', 'owned', 'payback', 'elasticity'],
  cash.filter((b) => Number.isFinite(b.paybackSeconds)).slice(0, 12).map((b) => [`${b.kind} ${b.id}`, String(b.owned), dur(b.paybackSeconds), b.elasticity.toFixed(3)]),
);
L.push('Spending the whole bank on one line:', '');
table(['line', 'units bought', 'income after'], bank.slice(0, 8).map((a) => [`${a.kind} ${a.id}`, sci(a.bought), `x${a.factor.toFixed(2)}`]));

L.push('## Numeric headroom', '');
L.push('Decades between each ever-growing number and the float ceiling (1.8e308). Past it the number becomes Infinity and every purchase and format breaks.', '');
table(['number', 'value', 'decades left'], heads.filter((h) => Number.isFinite(h.decadesLeft)).map((h) => [h.what, sci(h.value), h.decadesLeft.toFixed(0)]));

L.push(`## Watching it for ${HOURS}h with no purchases and no sale`, '');
for (const p of projections) {
  L.push(`Seed ${p.seed}: ${p.tournamentsWon}/${p.tournamentsPlayed} Invitationals won, all numbers finite: ${p.finite}.`, '');
  table(['hour', 'total cps', 'booked this hour'], p.rows.map((r) => [String(r.hour), sci(r.totalCps), share(r.booked)]));
}

// Play-forward runs ---------------------------------------------------------
for (const mode of ['idle', 'semi', 'active']) {
  const file = `${DIR}/play-${mode}.json`;
  if (!existsSync(file)) continue;
  const play = JSON.parse(readFileSync(file, 'utf8'));
  L.push(`## Selling now and playing on (${mode})`, '');
  L.push('Run 1 is the reference org, sold at once for its pending Legacy; the rows are the runs after it. A run is sold when Legacy would double or after four hours.', '');
  const rows: string[][] = [];
  const runs = Array.from(new Set<number>(play.samples.map((x: { run: number }) => x.run)));
  for (const run of runs) {
    const at = (t: number) => play.samples.filter((x: { run: number; runWall: number }) => x.run === run && x.runWall <= t).pop();
    const sale = play.sales.find((x: { run: number }) => x.run === run);
    const cell = (t: number) => (at(t) ? sci(at(t).totalCps) : '');
    rows.push([String(run), cell(600), cell(3600), cell(7200), sale ? dur(sale.runWall) : 'unsold', sale ? sci(sale.gained) : '', sale ? pct(sale.gained / Math.max(1, sale.levelAfter - sale.gained)) : '']);
  }
  table(['run', 'cps at 10m', 'at 1h', 'at 2h', 'sold after', 'legacy gained', 'as % of level'], rows);
}

writeFileSync(REPORT, L.join('\n'));
console.log(`wrote ${REPORT} and ${DIR}/static.json (baseline total ${sci(base.total)}, legacy sale worth ${sci(legacyFor(s.earnedTotal) - s.prestige.level)})`);
